POST http://localhost:3001/api/chat HTTP/1.1
Content-Type: application/json

{
  "role": "user",
  "content": "What is the capital of France?"
}

###

POST http://localhost:3001/api/chat-stream HTTP/1.1
Content-Type: application/json

{
  "role": "user",
  "content": "show me a short python script without explanation"
}